src/main/java/com/example/outsourcingproject/exception/ErrorCode.java
=> Feat: ãdev init

src/main/java/com/example/outsourcingproject/domain/menu/service/MenuService.java
=> fix: MenuService 수정

src/main/java/com/example/outsourcingproject/domain/user/enums/UserRoleEnum.java, src/main/java/com/example/outsourcingproject/domain/user/utils/JwtUtil.java
Feat: JwtUtil 생성, UserRoleEnum 스펠링 오타 수정
=> Feat: JwtUtil 생성, UserRoleEnum 스펠링 오타 수정

src/main/java/com/example/outsourcingproject/domain/review/service/ReviewService.java
=> Fix: import 수정

src/main/java/com/example/outsourcingproject/domain/order/controller/OrderController.java, src/main/java/com/example/outsourcingproject/domain/order/dto/CreateOrderRequestDto.java, src/main/java/com/example/outsourcingproject/domain/order/dto/CreateOrderResponseDto.java, src/main/java/com/example/outsourcingproject/domain/order/dto/dto.java, src/main/java/com/example/outsourcingproject/domain/order/entity/Order.java, src/main/java/com/example/outsourcingproject/domain/order/repository/OrderRepository.java, src/main/java/com/example/outsourcingproject/domain/order/service/OrderService.java, src/main/java/com/example/outsourcingproject/exception/ErrorCode.java, src/main/java/com/example/outsourcingproject/exception/common/MenuNotFoundException.java, src/main/java/com/example/outsourcingproject/exception/common/StoreNotFoundException.java
=> Feat: 주문 생성 API 완성, 예외 처리 추가

src/main/java/com/example/outsourcingproject/domain/order/enums/OrderStatus.java, src/main/java/com/example/outsourcingproject/domain/order/service/OrderService.java
Feat: 주문 상태 ENUM 추가
Fix: 주문 생성시 기본 상태 수정
=> Feat: 주문 상태 ENUM 추가, Fix: 주문 생성시 기본 상태 수정

src/main/java/com/example/outsourcingproject/domain/user/controller/UserController.java, src/main/java/com/example/outsourcingproject/domain/user/dto/Dto.java, src/main/java/com/example/outsourcingproject/domain/user/dto/request/UserSignUpRequestDto.java, src/main/java/com/example/outsourcingproject/domain/user/dto/response/UserSignUpResponseDto.java, src/main/java/com/example/outsourcingproject/domain/user/entity/User.java, src/main/java/com/example/outsourcingproject/domain/user/repository/UserRepository.java, src/main/java/com/example/outsourcingproject/domain/user/service/UserService.java, src/main/java/com/example/outsourcingproject/domain/user/utils/BCrypUtil.java
1. 추후 토큰 생성 구현해야 합니다.
2. 관리자 부분 dto에서 이렇게 받는게 맞는지 모르겠습니다.
검토 필요
=> Feat: User 회원가입 임시 구현

src/main/java/com/example/outsourcingproject/domain/menu/controller/MenuController.java, src/test/java/com/example/outsourcingproject/domain/menu/controller/MenuControllerTest.java, src/test/java/com/example/outsourcingproject/domain/menu/service/MenuServiceTest.java
Fix: MenuController userId 임시로 받아와서 빨간줄 없애기
=> Fix: MenuController userId 임시로 받아오기

src/main/java/com/example/outsourcingproject/domain/review/service/ReviewService.java
=> Fix: orderrepository 반영

src/main/java/com/example/outsourcingproject/domain/store/controller/StoreController.java, src/main/java/com/example/outsourcingproject/domain/store/dto/StoreCreateRequestDto.java, src/main/java/com/example/outsourcingproject/domain/store/dto/StoreCreateResponseDto.java, src/main/java/com/example/outsourcingproject/domain/store/entity/Store.java, src/main/java/com/example/outsourcingproject/domain/store/repository/StoreRepository.java, src/main/java/com/example/outsourcingproject/domain/store/service/StoreService.java, src/main/java/com/example/outsourcingproject/domain/user/service/UserService.java
=> Feat: Create Store

src/main/java/com/example/outsourcingproject/domain/review/service/ReviewService.java
=> Fix: userservice 반영

src/main/java/com/example/outsourcingproject/domain/order/entity/Order.java, src/main/java/com/example/outsourcingproject/domain/review/repository/ReviewRepository.java, src/main/java/com/example/outsourcingproject/domain/review/service/ReviewService.java, src/main/java/com/example/outsourcingproject/domain/user/utils/JwtUtil.java
=> Feat: All Create Done

build.gradle, src/main/java/com/example/outsourcingproject/config/SecurityConfig.java, src/main/java/com/example/outsourcingproject/config/SwaggerConfig.java, src/main/java/com/example/outsourcingproject/domain/store/controller/StoreController.java
=> Feat: swagger open

src/main/java/com/example/outsourcingproject/config/SecurityConfig.java, src/main/java/com/example/outsourcingproject/domain/store/dto/StoreCreateRequestDto.java, src/main/java/com/example/outsourcingproject/domain/store/dto/StoreCreateResponseDto.java, src/main/java/com/example/outsourcingproject/domain/store/entity/Store.java, src/main/java/com/example/outsourcingproject/domain/user/entity/User.java, src/main/java/com/example/outsourcingproject/domain/user/service/UserService.java
=> Fix: password and userSignUp

src/main/java/com/example/outsourcingproject/domain/review/service/ReviewService.java, src/main/java/com/example/outsourcingproject/exception/ErrorCode.java, src/main/java/com/example/outsourcingproject/exception/common/OrderNoDeivered.java, src/main/java/com/example/outsourcingproject/exception/common/OrderNotFoundException.java
=> Feat: 예외처리 추가

src/main/java/com/example/outsourcingproject/domain/review/repository/ReviewRepository.java, src/main/java/com/example/outsourcingproject/domain/review/service/ReviewService.java
=> Feat: 최신순 정렬 추가

src/main/java/com/example/outsourcingproject/domain/review/repository/ReviewRepository.java, src/main/java/com/example/outsourcingproject/domain/review/service/ReviewService.java
Fix: repository 매서드 변경
storeId를 store_storeId로 변경
=> Fix: repository 매서드 변경

src/main/java/com/example/outsourcingproject/domain/order/controller/OrderController.java, src/main/java/com/example/outsourcingproject/domain/order/dto/ChangeOrderStatusRequestDto.java, src/main/java/com/example/outsourcingproject/domain/order/dto/CreateOrderRequestDto.java, src/main/java/com/example/outsourcingproject/domain/order/dto/OrderListDto.java, src/main/java/com/example/outsourcingproject/domain/order/dto/OrderListResponseDto.java, src/main/java/com/example/outsourcingproject/domain/order/repository/OrderRepository.java, src/main/java/com/example/outsourcingproject/domain/order/service/OrderService.java
=> Feat: 주문 내역 조회 API 추가

src/main/java/com/example/outsourcingproject/domain/store/controller/StoreController.java, src/main/java/com/example/outsourcingproject/domain/store/dto/StoreCreateRequestDto.java, src/main/java/com/example/outsourcingproject/domain/store/dto/StoreCreateRequestWithUserDto.java, src/main/java/com/example/outsourcingproject/domain/store/dto/StoreDetailResponseDto.java, src/main/java/com/example/outsourcingproject/domain/store/dto/StoreListResponseDto.java, src/main/java/com/example/outsourcingproject/domain/store/dto/StoreResponseDto.java, src/main/java/com/example/outsourcingproject/domain/store/dto/StoreUpdateRequestDto.java, src/main/java/com/example/outsourcingproject/domain/store/repository/StoreRepository.java, src/main/java/com/example/outsourcingproject/domain/store/service/StoreService.java
=> Feat: Store get temporary

src/main/java/com/example/outsourcingproject/domain/store/controller/StoreController.java, src/main/java/com/example/outsourcingproject/domain/store/dto/StoreCloseResponseDto.java, src/main/java/com/example/outsourcingproject/domain/store/entity/Store.java, src/main/java/com/example/outsourcingproject/domain/store/repository/StoreRepository.java, src/main/java/com/example/outsourcingproject/domain/store/service/StoreService.java
=> Feat: Store Delete

src/main/java/com/example/outsourcingproject/domain/review/controller/ReviewController.java, src/main/java/com/example/outsourcingproject/domain/review/service/ReviewService.java
=> Fix: URL 수정

src/main/java/com/example/outsourcingproject/config/SecurityConfig.java
Feat: 시큐리티  어노테이션 EnableMethodSecurity 추가
=> Feat: 시큐리티  어노테이션 EnableMethodSecurity 추가

src/main/java/com/example/outsourcingproject/config/SwaggerConfig.java, src/main/java/com/example/outsourcingproject/domain/store/controller/StoreController.java
=> Fix: Swagger Config Fix

src/main/java/com/example/outsourcingproject/domain/review/service/ReviewService.java
=> Feat: 별점 유효성 추가

src/main/java/com/example/outsourcingproject/domain/review/service/ReviewService.java
=> Fix: 별점 유효성 Exception 변경

src/main/java/com/example/outsourcingproject/domain/review/controller/ReviewController.java
Fix: userId RequestParam에서 @AuthenticationPrincipal으로 변경
=> Fix: userId RequestParam에서 @AuthenticationPrincipal으로 변경

src/main/java/com/example/outsourcingproject/exception/GlobalExceptionHandler.java
- handleException()이 Spring Sequrity 예외처리와 중복되어서 삭제함
=> Fix: 문제가 되는 예외 처리 삭제

src/main/java/com/example/outsourcingproject/domain/menu/controller/MenuController.java
=> Comment: 설명 추가

src/test/java/com/example/outsourcingproject/domain/review/service/ReviewServiceTest.java
=> feat: 테스트 생성

src/main/java/com/example/outsourcingproject/domain/user/enums/UserRoleEnum.java, src/test/java/com/example/outsourcingproject/domain/store/controller/StoreControllerTest.java, src/test/java/com/example/outsourcingproject/domain/store/service/StoreServiceTest.java
=> Feat: Store Test Code
